# Generated by Django 6.0.2 on 2026-03-31 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='quantite_initiale',
        ),
    ]
