# Generated by Django 6.0.2 on 2026-05-04 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_exploitation_mouvement_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
