# Generated by Django 6.0.2 on 2026-04-03 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_lot_quantite_initiale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fournisseur', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exploitation')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='core.lot')),
            ],
        ),
    ]
