# Generated by Django 6.0.2 on 2026-04-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
