# Generated by Django 6.0.2 on 2026-04-12 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_depense_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.exploitation')),
            ],
        ),
    ]
