# Generated by Django 6.0.2 on 2026-04-13 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_client_mouvement_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='core.client'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.client')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exploitation')),
            ],
        ),
        migrations.CreateModel(
            name='Lettrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lettrages', to='core.vente')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lettrages', to='core.payment')),
            ],
        ),
    ]
