# Generated by Django 6.0.2 on 2026-09-21 21:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_client_pays_client_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='age_arrivee_semaines',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='date_debut_ponte',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='statut_production',
            field=models.CharField(choices=[('ELEVAGE', 'Élevage'), ('PONTE', 'Ponte'), ('REFORME', 'Réforme'), ('TERMINE', 'Terminé')], default='ELEVAGE', max_length=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='type_production',
            field=models.CharField(choices=[('CHAIR', 'Élevage de chair'), ('OEUFS', 'Production d’œufs'), ('REPRODUCTION', 'Reproduction'), ('AUTRE', 'Autre')], default='CHAIR', max_length=20),
        ),
        migrations.CreateModel(
            name='CollecteOeufs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collecte_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre_collecte', models.PositiveIntegerField()),
                ('nombre_casses', models.PositiveIntegerField(default=0)),
                ('nombre_declasses', models.PositiveIntegerField(default=0)),
                ('nombre_consommes_donnes', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes_oeufs_creees', to=settings.AUTH_USER_MODEL)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectes_oeufs', to='core.exploitation')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectes_oeufs', to='core.lot')),
            ],
            options={
                'ordering': ('-collecte_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ConsommationAliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantite_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('prix_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consommations_aliment_creees', to=settings.AUTH_USER_MODEL)),
                ('depense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consommation_aliment', to='core.depense')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations_aliment', to='core.exploitation')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations_aliment', to='core.lot')),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='MouvementOeufs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('PRODUCTION', 'Production'), ('VENTE', 'Vente'), ('CONSOMMATION', 'Consommation'), ('DON', 'Don'), ('CASSE', 'Casse après stockage'), ('PERTE', 'Perte'), ('AJUSTEMENT', "Ajustement d'inventaire")], max_length=20)),
                ('quantite', models.IntegerField()),
                ('quantite_signee', models.IntegerField(editable=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collecte', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvement_stock', to='core.collecteoeufs')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_oeufs_crees', to=settings.AUTH_USER_MODEL)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_oeufs', to='core.exploitation')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_oeufs', to='core.lot')),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='VenteOeufs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditionnement', models.CharField(choices=[('UNITE', 'Unité'), ('DOUZAINE', 'Douzaine'), ('PLATEAU', 'Plateau'), ('CARTON', 'Carton')], max_length=20)),
                ('nombre_conditionnements', models.PositiveIntegerField()),
                ('oeufs_par_conditionnement', models.PositiveIntegerField(default=1)),
                ('nombre_oeufs', models.PositiveIntegerField()),
                ('prix_unitaire_conditionnement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes_oeufs', to='core.exploitation')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes_oeufs', to='core.lot')),
                ('vente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_oeufs', to='core.vente')),
            ],
        ),
    ]
