# Generated by Django 6.0.2 on 2026-09-21 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lot_age_arrivee_semaines_lot_date_debut_ponte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementoeufs',
            name='vente_oeufs',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvement_stock', to='core.venteoeufs'),
        ),
    ]
