# Generated by Django 6.0.2 on 2026-09-28 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_peseeproduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationMouvementOeufs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collecte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_sortie', to='core.collecteoeufs')),
                ('mouvement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='core.mouvementoeufs')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantite__gt', 0)), name='affectation_oeufs_quantite_positive'), models.UniqueConstraint(fields=('mouvement', 'collecte'), name='affectation_oeufs_origine_unique')],
            },
        ),
    ]
