# Generated by Django 6.0.2 on 2026-09-28 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_affectationmouvementoeufs'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvement',
            name='vente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvement_animal', to='core.vente'),
        ),
        migrations.AlterField(
            model_name='venteoeufs',
            name='conditionnement',
            field=models.CharField(choices=[('UNITE', 'Unité'), ('DOUZAINE', 'Douzaine'), ('PLATEAU', 'Plateau'), ('CARTON', 'Carton'), ('COMPOSE', 'Alvéoles et œufs supplémentaires')], max_length=20),
        ),
    ]
