# Generated by Django 6.0.2 on 2026-10-06 21:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_mouvement_lot_origine'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exploitation',
            name='offline_policy_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exploitation',
            name='write_generation',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lettrage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='report',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To do'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='TODO', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vente',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venteoeufs',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exploitation_id', models.BigIntegerField(db_index=True)),
                ('actor_user_id', models.BigIntegerField(null=True)),
                ('decision_actor_id', models.BigIntegerField(null=True)),
                ('device_id', models.BigIntegerField(null=True)),
                ('transport_identity', models.CharField(default='USER', max_length=30)),
                ('category', models.CharField(default='BUSINESS', max_length=20)),
                ('action', models.CharField(max_length=40)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('local_entity_id', models.UUIDField(null=True)),
                ('operation_id', models.UUIDField(null=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('before_data', models.JSONField(default=dict)),
                ('after_data', models.JSONField(default=dict)),
                ('business_occurred_at', models.DateTimeField(null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applied_at', models.DateTimeField(null=True)),
                ('reason_code', models.CharField(blank=True, max_length=30)),
                ('reason_text', models.TextField(blank=True)),
                ('source', models.CharField(default='ONLINE', max_length=10)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['exploitation_id', 'received_at'], name='audit_tenant_received_idx'), models.Index(fields=['exploitation_id', 'entity_type', 'entity_id'], name='audit_tenant_entity_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_uuid', models.UUIDField(unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('ANDROID', 'Android')], default='ANDROID', max_length=20)),
                ('public_key', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='PENDING', max_length=12)),
                ('is_primary_writer', models.BooleanField(default=False)),
                ('write_generation', models.PositiveIntegerField(default=1)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_full_sync_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=255)),
                ('activated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.exploitation')),
                ('revoked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deviceregistration')),
            ],
        ),
        migrations.CreateModel(
            name='ExploitationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('OPERATEUR', 'Operator')], max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('can_reconcile', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.exploitation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capabilities', models.JSONField(default=dict)),
                ('rights_version', models.PositiveIntegerField()),
                ('write_generation', models.PositiveIntegerField()),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_authorizations', to='core.deviceregistration')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_authorizations', to='core.exploitationmembership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='deviceregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_writer', True), ('status', 'ACTIVE')), fields=('exploitation',), name='one_active_primary_device'),
        ),
        migrations.AddConstraint(
            model_name='deviceregistration',
            constraint=models.CheckConstraint(condition=models.Q(('is_primary_writer', False), ('status', 'ACTIVE'), _connector='OR'), name='primary_device_must_be_active'),
        ),
        migrations.AddConstraint(
            model_name='exploitationmembership',
            constraint=models.UniqueConstraint(fields=('user', 'exploitation'), name='membership_user_tenant_unique'),
        ),
    ]
