# Generated by Django 6.0.2 on 2026-10-07 11:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_audit_append_only_postgresql'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTransportChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('RECEIVE', 'Receive'), ('STATUS', 'Status')], max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deviceregistration')),
            ],
        ),
        migrations.CreateModel(
            name='TerrainSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_operation_id', models.UUIDField()),
                ('local_sequence', models.PositiveBigIntegerField()),
                ('author_user_id', models.PositiveBigIntegerField()),
                ('author_membership_id', models.PositiveBigIntegerField()),
                ('device_generation', models.PositiveIntegerField()),
                ('entity_type', models.CharField(max_length=32)),
                ('operation_type', models.CharField(max_length=20)),
                ('local_entity_id', models.UUIDField(null=True)),
                ('payload', models.JSONField()),
                ('dependencies', models.JSONField(default=list)),
                ('expected_server_version', models.CharField(blank=True, max_length=100)),
                ('business_occurred_at', models.DateTimeField()),
                ('local_recorded_at', models.DateTimeField()),
                ('declaration_digest', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.deviceregistration')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.exploitation')),
                ('offline_authorization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.offlineauthorization')),
            ],
        ),
        migrations.CreateModel(
            name='TerrainOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_status', models.CharField(choices=[('UNREVIEWED', 'UNREVIEWED'), ('WAITING_DEPENDENCY', 'WAITING_DEPENDENCY'), ('CONFIRMED', 'CONFIRMED'), ('NEEDS_RECONCILIATION', 'NEEDS_RECONCILIATION'), ('NOT_APPLIED', 'NOT_APPLIED'), ('SUPERSEDED', 'SUPERSEDED')], default='UNREVIEWED', max_length=24)),
                ('reason_code', models.CharField(blank=True, max_length=50)),
                ('reason_text', models.TextField(blank=True)),
                ('server_entity_type', models.CharField(blank=True, max_length=40)),
                ('server_entity_id', models.CharField(blank=True, max_length=100)),
                ('server_version', models.CharField(blank=True, max_length=100)),
                ('applied_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outcome', to='core.terrainsubmission')),
            ],
        ),
        migrations.AddIndex(
            model_name='terrainsubmission',
            index=models.Index(fields=['exploitation', 'received_at'], name='terrain_farm_received_idx'),
        ),
        migrations.AddConstraint(
            model_name='terrainsubmission',
            constraint=models.UniqueConstraint(fields=('exploitation', 'client_operation_id'), name='terrain_farm_operation_unique'),
        ),
        migrations.AddConstraint(
            model_name='terrainsubmission',
            constraint=models.UniqueConstraint(fields=('device', 'local_sequence'), name='terrain_device_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='terrainsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('local_sequence__gt', 0)), name='terrain_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='terrainoutcome',
            constraint=models.CheckConstraint(condition=models.Q(('business_status__in', ('UNREVIEWED', 'WAITING_DEPENDENCY', 'CONFIRMED', 'NEEDS_RECONCILIATION', 'NOT_APPLIED', 'SUPERSEDED'))), name='terrain_business_status_valid'),
        ),
    ]
