# Generated by Django 6.0.2 on 2026-10-07 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_terrain_declaration_append_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerrainEntityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=32)),
                ('local_entity_id', models.UUIDField()),
                ('server_entity_id', models.PositiveBigIntegerField()),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.exploitation')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.terrainsubmission')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exploitation', 'entity_type', 'local_entity_id'), name='terrain_farm_entity_mapping_unique')],
            },
        ),
    ]
