# Generated by Django 6.0.2 on 2026-10-07 14:46

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models
from decimal import Decimal, InvalidOperation


def validate_existing_money(apps, schema_editor):
    # Refuse real rounding, overflow and non-finite legacy values. No UPDATE
    # is issued: PostgreSQL's numeric conversion preserves validated cents.
    for name in ('Payment', 'Lettrage'):
        model = apps.get_model('core', name)
        for pk, value in model.objects.using(schema_editor.connection.alias).values_list('pk', 'montant').iterator():
            try:
                amount = Decimal(str(value))
                valid = (amount.is_finite() and Decimal('0') <= amount <= Decimal('9999999999.99') and
                    abs(amount - amount.quantize(Decimal('0.01'))) <= Decimal('0.0000001'))
            except (InvalidOperation, ValueError, TypeError):
                valid = False
            if not valid:
                raise RuntimeError(f'{name} #{pk}: monetary migration needs explicit reconciliation; no conversion performed.')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_exploitation_business_revision_and_more'),
    ]

    operations = [
        migrations.RunPython(validate_existing_money, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='lettrage',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='EncaissementTerrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_occurred_at', models.DateTimeField()),
                ('montant_recu', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_affecte', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_a_rapprocher', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(choices=[('ESPECES', 'ESPECES'), ('MOBILE_MONEY', 'MOBILE_MONEY'), ('VIREMENT', 'VIREMENT'), ('CHEQUE', 'CHEQUE')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.exploitation')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.payment')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.terrainsubmission')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('montant_recu__gt', 0)), name='terrain_cash_positive'), models.CheckConstraint(condition=models.Q(('montant_a_rapprocher__gte', 0), ('montant_affecte__gte', 0)), name='terrain_cash_parts_positive'), models.CheckConstraint(condition=models.Q(('montant_recu', django.db.models.expressions.CombinedExpression(models.F('montant_affecte'), '+', models.F('montant_a_rapprocher')))), name='terrain_cash_parts_equal_received')],
            },
        ),
    ]
