# Generated by Django 6.0.2 on 2026-10-07 16:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_cash_physical_receipt_immutable'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrainoutcome',
            name='decision_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TerrainDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_uuid', models.UUIDField()),
                ('decision_actor_id', models.PositiveBigIntegerField()),
                ('action', models.CharField(max_length=24)),
                ('reason', models.TextField()),
                ('effective_payload', models.JSONField(default=dict)),
                ('request_digest', models.CharField(max_length=64)),
                ('before_data', models.JSONField(default=dict)),
                ('after_data', models.JSONField(default=dict)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.exploitation')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='core.terrainsubmission')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exploitation', 'decision_uuid'), name='terrain_farm_decision_unique')],
            },
        ),
    ]
