# Generated by Django 6.0.2 on 2026-10-07 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_terrain_decision_append_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerrainStockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_uuid', models.UUIDField()),
                ('kind', models.CharField(choices=[('ANIMAL', 'Animal'), ('EGG', 'Egg')], max_length=8)),
                ('signed_quantity', models.BigIntegerField()),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='lettrage',
            name='void_decision_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='lettrage',
            name='voided_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='void_decision_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='voided_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='venteoeufs',
            name='void_decision_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='venteoeufs',
            name='voided_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='lettrage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('void_decision_uuid__isnull', True), ('voided_at__isnull', True)), models.Q(('void_decision_uuid__isnull', False), ('voided_at__isnull', False)), _connector='OR'), name='core_lettrage_void_consistent'),
        ),
        migrations.AddConstraint(
            model_name='vente',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('void_decision_uuid__isnull', True), ('voided_at__isnull', True)), models.Q(('void_decision_uuid__isnull', False), ('voided_at__isnull', False)), _connector='OR'), name='core_vente_void_consistent'),
        ),
        migrations.AddConstraint(
            model_name='venteoeufs',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('void_decision_uuid__isnull', True), ('voided_at__isnull', True)), models.Q(('void_decision_uuid__isnull', False), ('voided_at__isnull', False)), _connector='OR'), name='core_venteoeufs_void_consistent'),
        ),
        migrations.AddField(
            model_name='terrainstockadjustment',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.collecteoeufs'),
        ),
        migrations.AddField(
            model_name='terrainstockadjustment',
            name='exploitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.exploitation'),
        ),
        migrations.AddField(
            model_name='terrainstockadjustment',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.lot'),
        ),
        migrations.AddField(
            model_name='terrainstockadjustment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.terrainsubmission'),
        ),
        migrations.AddIndex(
            model_name='terrainstockadjustment',
            index=models.Index(fields=['exploitation', 'lot', 'kind'], name='terrain_adjustment_lot_idx'),
        ),
        migrations.AddConstraint(
            model_name='terrainstockadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('signed_quantity', 0), _negated=True), name='terrain_adjustment_nonzero'),
        ),
    ]
