# Generated by Django 6.0.2 on 2026-10-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_stock_compensation_append_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommationaliment',
            name='void_decision_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='consommationaliment',
            name='voided_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='depense',
            name='void_decision_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='depense',
            name='voided_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='peseeproduction',
            name='void_decision_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='peseeproduction',
            name='voided_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='consommationaliment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('void_decision_uuid__isnull', True), ('voided_at__isnull', True)), models.Q(('void_decision_uuid__isnull', False), ('voided_at__isnull', False)), _connector='OR'), name='core_consommationaliment_void_consistent'),
        ),
        migrations.AddConstraint(
            model_name='depense',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('void_decision_uuid__isnull', True), ('voided_at__isnull', True)), models.Q(('void_decision_uuid__isnull', False), ('voided_at__isnull', False)), _connector='OR'), name='core_depense_void_consistent'),
        ),
        migrations.AddConstraint(
            model_name='peseeproduction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('void_decision_uuid__isnull', True), ('voided_at__isnull', True)), models.Q(('void_decision_uuid__isnull', False), ('voided_at__isnull', False)), _connector='OR'), name='core_peseeproduction_void_consistent'),
        ),
    ]
