# Generated by Django 6.0.2 on 2026-10-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_terrain_origin_reversals'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='void_decision_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='voided_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('void_decision_uuid__isnull', True), ('voided_at__isnull', True)), models.Q(('void_decision_uuid__isnull', False), ('voided_at__isnull', False)), _connector='OR'), name='core_client_void_consistent'),
        ),
    ]
